// Mocks generated by Mockito 5.2.0 from annotations
// in crosscheck/test/features/main/data/repositories/main_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:crosscheck/features/main/data/datasource/main_local_data_source.dart'
    as _i3;
import 'package:crosscheck/features/main/data/model/bottom_navigation_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeBottomNavigationModel_0 extends _i1.Fake
    implements _i2.BottomNavigationModel {}

/// A class which mocks [MainLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainLocalDataSource extends _i1.Mock
    implements _i3.MainLocalDataSource {
  MockMainLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BottomNavigationModel> getActiveBottomNavigation() =>
      (super.noSuchMethod(Invocation.method(#getActiveBottomNavigation, []),
              returnValue: Future<_i2.BottomNavigationModel>.value(
                  _FakeBottomNavigationModel_0()))
          as _i4.Future<_i2.BottomNavigationModel>);
  @override
  _i4.Future<void> setActiveBottomNavigation(
          _i2.BottomNavigationModel? param) =>
      (super.noSuchMethod(
          Invocation.method(#setActiveBottomNavigation, [param]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}
