// Mocks generated by Mockito 5.2.0 from annotations
// in crosscheck/test/features/main/presentation/view/main_view_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i20;

import 'package:crosscheck/features/authentication/presentation/authentication/bloc/authentication_bloc.dart'
    as _i19;
import 'package:crosscheck/features/authentication/presentation/authentication/bloc/authentication_event.dart'
    as _i21;
import 'package:crosscheck/features/authentication/presentation/authentication/bloc/authentication_state.dart'
    as _i2;
import 'package:crosscheck/features/dashboard/domain/usecases/get_dashboard_usecase.dart'
    as _i6;
import 'package:crosscheck/features/dashboard/presentation/bloc/dashboard_bloc.dart'
    as _i25;
import 'package:crosscheck/features/dashboard/presentation/bloc/dashboard_event.dart'
    as _i26;
import 'package:crosscheck/features/dashboard/presentation/bloc/dashboard_state.dart'
    as _i7;
import 'package:crosscheck/features/main/domain/usecase/get_active_bottom_navigation_usecase.dart'
    as _i3;
import 'package:crosscheck/features/main/domain/usecase/set_active_bottom_navigation_usecase.dart'
    as _i4;
import 'package:crosscheck/features/main/presentation/bloc/main_bloc.dart'
    as _i23;
import 'package:crosscheck/features/main/presentation/bloc/main_event.dart'
    as _i24;
import 'package:crosscheck/features/main/presentation/bloc/main_state.dart'
    as _i5;
import 'package:crosscheck/features/profile/domain/usecases/get_profile_usecase.dart'
    as _i11;
import 'package:crosscheck/features/profile/presentation/bloc/profile_bloc.dart'
    as _i29;
import 'package:crosscheck/features/profile/presentation/bloc/profile_event.dart'
    as _i30;
import 'package:crosscheck/features/profile/presentation/bloc/profile_state.dart'
    as _i12;
import 'package:crosscheck/features/settings/domain/usecase/get_theme_usecase.dart'
    as _i9;
import 'package:crosscheck/features/settings/domain/usecase/set_theme_usecase.dart'
    as _i8;
import 'package:crosscheck/features/settings/presentation/bloc/settings_bloc.dart'
    as _i27;
import 'package:crosscheck/features/settings/presentation/bloc/settings_event.dart'
    as _i28;
import 'package:crosscheck/features/settings/presentation/bloc/settings_state.dart'
    as _i10;
import 'package:crosscheck/features/task/domain/entities/monthly_task_entity.dart'
    as _i33;
import 'package:crosscheck/features/task/domain/entities/task_entity.dart'
    as _i35;
import 'package:crosscheck/features/task/domain/usecases/get_history_usecase.dart'
    as _i13;
import 'package:crosscheck/features/task/domain/usecases/get_initial_task_by_date_usecase.dart'
    as _i16;
import 'package:crosscheck/features/task/domain/usecases/get_monthly_task_usecase.dart'
    as _i17;
import 'package:crosscheck/features/task/domain/usecases/get_more_history_usecase.dart'
    as _i14;
import 'package:crosscheck/features/task/domain/usecases/get_refresh_history_usecase.dart'
    as _i15;
import 'package:crosscheck/features/task/presentation/bloc/monthly_task_model.dart'
    as _i32;
import 'package:crosscheck/features/task/presentation/bloc/task_bloc.dart'
    as _i31;
import 'package:crosscheck/features/task/presentation/bloc/task_event.dart'
    as _i36;
import 'package:crosscheck/features/task/presentation/bloc/task_model.dart'
    as _i34;
import 'package:crosscheck/features/task/presentation/bloc/task_state.dart'
    as _i18;
import 'package:flutter_bloc/flutter_bloc.dart' as _i22;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAuthenticationState_0 extends _i1.Fake
    implements _i2.AuthenticationState {}

class _FakeGetActiveBottomNavigationUsecase_1 extends _i1.Fake
    implements _i3.GetActiveBottomNavigationUsecase {}

class _FakeSetActiveBottomNavigationUsecase_2 extends _i1.Fake
    implements _i4.SetActiveBottomNavigationUsecase {}

class _FakeMainState_3 extends _i1.Fake implements _i5.MainState {}

class _FakeGetDashboardUsecase_4 extends _i1.Fake
    implements _i6.GetDashboardUsecase {}

class _FakeDashboardState_5 extends _i1.Fake implements _i7.DashboardState {}

class _FakeSetThemeUsecase_6 extends _i1.Fake implements _i8.SetThemeUsecase {}

class _FakeGetThemeUsecase_7 extends _i1.Fake implements _i9.GetThemeUsecase {}

class _FakeSettingsState_8 extends _i1.Fake implements _i10.SettingsState {}

class _FakeGetProfileUsecase_9 extends _i1.Fake
    implements _i11.GetProfileUsecase {}

class _FakeProfileState_10 extends _i1.Fake implements _i12.ProfileState {}

class _FakeGetHistoryUsecase_11 extends _i1.Fake
    implements _i13.GetHistoryUsecase {}

class _FakeGetMoreHistoryUsecase_12 extends _i1.Fake
    implements _i14.GetMoreHistoryUsecase {}

class _FakeGetRefreshHistoryUsecase_13 extends _i1.Fake
    implements _i15.GetRefreshHistoryUsecase {}

class _FakeGetInitialTaskByDateUsecase_14 extends _i1.Fake
    implements _i16.GetInitialTaskByDateUsecase {}

class _FakeGetMonthlyTaskUsecase_15 extends _i1.Fake
    implements _i17.GetMonthlyTaskUsecase {}

class _FakeTaskState_16 extends _i1.Fake implements _i18.TaskState {}

/// A class which mocks [AuthenticationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationBloc extends _i1.Mock
    implements _i19.AuthenticationBloc {
  MockAuthenticationBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeAuthenticationState_0()) as _i2.AuthenticationState);
  @override
  _i20.Stream<_i2.AuthenticationState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i2.AuthenticationState>.empty())
          as _i20.Stream<_i2.AuthenticationState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i21.AuthenticationEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i21.AuthenticationEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i2.AuthenticationState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i21.AuthenticationEvent>(
          _i22.EventHandler<E, _i2.AuthenticationState>? handler,
          {_i22.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i22.Transition<_i21.AuthenticationEvent, _i2.AuthenticationState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i20.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i20.Future<void>);
  @override
  void onChange(_i22.Change<_i2.AuthenticationState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MainBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainBloc extends _i1.Mock implements _i23.MainBloc {
  MockMainBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetActiveBottomNavigationUsecase get getActiveBottomNavigationUsecase =>
      (super.noSuchMethod(Invocation.getter(#getActiveBottomNavigationUsecase),
              returnValue: _FakeGetActiveBottomNavigationUsecase_1())
          as _i3.GetActiveBottomNavigationUsecase);
  @override
  _i4.SetActiveBottomNavigationUsecase get setActiveBottomNavigationUsecase =>
      (super.noSuchMethod(Invocation.getter(#setActiveBottomNavigationUsecase),
              returnValue: _FakeSetActiveBottomNavigationUsecase_2())
          as _i4.SetActiveBottomNavigationUsecase);
  @override
  _i5.MainState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeMainState_3()) as _i5.MainState);
  @override
  _i20.Stream<_i5.MainState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i5.MainState>.empty())
          as _i20.Stream<_i5.MainState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i24.MainEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i24.MainEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i5.MainState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i24.MainEvent>(
          _i22.EventHandler<E, _i5.MainState>? handler,
          {_i22.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i22.Transition<_i24.MainEvent, _i5.MainState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i20.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i20.Future<void>);
  @override
  void onChange(_i22.Change<_i5.MainState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [DashboardBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardBloc extends _i1.Mock implements _i25.DashboardBloc {
  MockDashboardBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetDashboardUsecase get getDashboardUsecase => (super.noSuchMethod(
      Invocation.getter(#getDashboardUsecase),
      returnValue: _FakeGetDashboardUsecase_4()) as _i6.GetDashboardUsecase);
  @override
  _i7.DashboardState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeDashboardState_5()) as _i7.DashboardState);
  @override
  _i20.Stream<_i7.DashboardState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i7.DashboardState>.empty())
          as _i20.Stream<_i7.DashboardState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  String getProgress(double? rawProgress) =>
      (super.noSuchMethod(Invocation.method(#getProgress, [rawProgress]),
          returnValue: '') as String);
  @override
  void add(_i26.DashboardEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i26.DashboardEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i7.DashboardState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i26.DashboardEvent>(
          _i22.EventHandler<E, _i7.DashboardState>? handler,
          {_i22.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i22.Transition<_i26.DashboardEvent, _i7.DashboardState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i20.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i20.Future<void>);
  @override
  void onChange(_i22.Change<_i7.DashboardState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [SettingsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsBloc extends _i1.Mock implements _i27.SettingsBloc {
  MockSettingsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.SetThemeUsecase get setThemeUsecase =>
      (super.noSuchMethod(Invocation.getter(#setThemeUsecase),
          returnValue: _FakeSetThemeUsecase_6()) as _i8.SetThemeUsecase);
  @override
  _i9.GetThemeUsecase get getThemeUsecase =>
      (super.noSuchMethod(Invocation.getter(#getThemeUsecase),
          returnValue: _FakeGetThemeUsecase_7()) as _i9.GetThemeUsecase);
  @override
  _i10.SettingsState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeSettingsState_8()) as _i10.SettingsState);
  @override
  _i20.Stream<_i10.SettingsState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i10.SettingsState>.empty())
          as _i20.Stream<_i10.SettingsState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i28.SettingsEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i28.SettingsEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i10.SettingsState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i28.SettingsEvent>(
          _i22.EventHandler<E, _i10.SettingsState>? handler,
          {_i22.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i22.Transition<_i28.SettingsEvent, _i10.SettingsState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i20.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i20.Future<void>);
  @override
  void onChange(_i22.Change<_i10.SettingsState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [ProfileBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileBloc extends _i1.Mock implements _i29.ProfileBloc {
  MockProfileBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.GetProfileUsecase get getProfileUsecase =>
      (super.noSuchMethod(Invocation.getter(#getProfileUsecase),
          returnValue: _FakeGetProfileUsecase_9()) as _i11.GetProfileUsecase);
  @override
  _i12.ProfileState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeProfileState_10()) as _i12.ProfileState);
  @override
  _i20.Stream<_i12.ProfileState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i12.ProfileState>.empty())
          as _i20.Stream<_i12.ProfileState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i30.ProfileEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i30.ProfileEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i12.ProfileState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i30.ProfileEvent>(
          _i22.EventHandler<E, _i12.ProfileState>? handler,
          {_i22.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i22.Transition<_i30.ProfileEvent, _i12.ProfileState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i20.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i20.Future<void>);
  @override
  void onChange(_i22.Change<_i12.ProfileState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [TaskBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskBloc extends _i1.Mock implements _i31.TaskBloc {
  MockTaskBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.GetHistoryUsecase get getHistoryUsecase =>
      (super.noSuchMethod(Invocation.getter(#getHistoryUsecase),
          returnValue: _FakeGetHistoryUsecase_11()) as _i13.GetHistoryUsecase);
  @override
  _i14.GetMoreHistoryUsecase get getMoreHistoryUsecase =>
      (super.noSuchMethod(Invocation.getter(#getMoreHistoryUsecase),
              returnValue: _FakeGetMoreHistoryUsecase_12())
          as _i14.GetMoreHistoryUsecase);
  @override
  _i15.GetRefreshHistoryUsecase get getRefreshHistoryUsecase =>
      (super.noSuchMethod(Invocation.getter(#getRefreshHistoryUsecase),
              returnValue: _FakeGetRefreshHistoryUsecase_13())
          as _i15.GetRefreshHistoryUsecase);
  @override
  _i16.GetInitialTaskByDateUsecase get getInitialTaskByDateUsecase =>
      (super.noSuchMethod(Invocation.getter(#getInitialTaskByDateUsecase),
              returnValue: _FakeGetInitialTaskByDateUsecase_14())
          as _i16.GetInitialTaskByDateUsecase);
  @override
  _i17.GetMonthlyTaskUsecase get getMonthlyTaskUsecase =>
      (super.noSuchMethod(Invocation.getter(#getMonthlyTaskUsecase),
              returnValue: _FakeGetMonthlyTaskUsecase_15())
          as _i17.GetMonthlyTaskUsecase);
  @override
  _i18.TaskState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeTaskState_16()) as _i18.TaskState);
  @override
  _i20.Stream<_i18.TaskState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i18.TaskState>.empty())
          as _i20.Stream<_i18.TaskState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  List<_i32.MonthlyTaskModel> getMonthlyTaskModel(
          List<_i33.MonthlyTaskEntity>? entities) =>
      (super.noSuchMethod(Invocation.method(#getMonthlyTaskModel, [entities]),
              returnValue: <_i32.MonthlyTaskModel>[])
          as List<_i32.MonthlyTaskModel>);
  @override
  List<_i34.TaskModel> getTaskModel(List<_i35.TaskEntity>? entities) =>
      (super.noSuchMethod(Invocation.method(#getTaskModel, [entities]),
          returnValue: <_i34.TaskModel>[]) as List<_i34.TaskModel>);
  @override
  dynamic getTask(_i36.TaskEvent? event, _i22.Emitter<_i18.TaskState>? emit,
          _i31.Usecase? usecase) =>
      super.noSuchMethod(Invocation.method(#getTask, [event, emit, usecase]));
  @override
  dynamic getMonthlyTask(_i36.TaskEvent? event,
          _i22.Emitter<_i18.TaskState>? emit, _i31.Usecase? usecase) =>
      super.noSuchMethod(
          Invocation.method(#getMonthlyTask, [event, emit, usecase]));
  @override
  void add(_i36.TaskEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i36.TaskEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i18.TaskState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i36.TaskEvent>(
          _i22.EventHandler<E, _i18.TaskState>? handler,
          {_i22.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i22.Transition<_i36.TaskEvent, _i18.TaskState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i20.Future<void> close() => (super.noSuchMethod(
      Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i20.Future<void>);
  @override
  void onChange(_i22.Change<_i18.TaskState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}
