// Mocks generated by Mockito 5.2.0 from annotations
// in crosscheck/integration_test/features/authentication/login/login_view_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:crosscheck/core/error/failure.dart' as _i7;
import 'package:crosscheck/core/param/param.dart' as _i14;
import 'package:crosscheck/features/authentication/data/models/request/login_params.dart'
    as _i9;
import 'package:crosscheck/features/authentication/domain/entities/authentication_entity.dart'
    as _i8;
import 'package:crosscheck/features/authentication/domain/repositories/authentication_repository.dart'
    as _i2;
import 'package:crosscheck/features/authentication/domain/usecases/login_usecase.dart'
    as _i5;
import 'package:crosscheck/features/main/data/model/bottom_navigation_model.dart'
    as _i12;
import 'package:crosscheck/features/main/domain/entities/bottom_navigation_entity.dart'
    as _i11;
import 'package:crosscheck/features/main/domain/repositories/main_repository.dart'
    as _i4;
import 'package:crosscheck/features/main/domain/usecase/get_active_bottom_navigation_usecase.dart'
    as _i13;
import 'package:crosscheck/features/main/domain/usecase/set_active_bottom_navigation_usecase.dart'
    as _i10;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAuthenticationRepository_0 extends _i1.Fake
    implements _i2.AuthenticationRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

class _FakeMainRepository_2 extends _i1.Fake implements _i4.MainRepository {}

/// A class which mocks [LoginUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUsecase extends _i1.Mock implements _i5.LoginUsecase {
  MockLoginUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthenticationRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue: _FakeAuthenticationRepository_0())
          as _i2.AuthenticationRepository);
  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.AuthenticationEntity>> call(
          _i9.LoginParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<
                      _i3.Either<_i7.Failure, _i8.AuthenticationEntity>>.value(
                  _FakeEither_1<_i7.Failure, _i8.AuthenticationEntity>()))
          as _i6.Future<_i3.Either<_i7.Failure, _i8.AuthenticationEntity>>);
}

/// A class which mocks [SetActiveBottomNavigationUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetActiveBottomNavigationUsecase extends _i1.Mock
    implements _i10.SetActiveBottomNavigationUsecase {
  MockSetActiveBottomNavigationUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MainRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMainRepository_2()) as _i4.MainRepository);
  @override
  _i6.Future<_i3.Either<_i7.Failure, _i11.BottomNavigationEntity>> call(
          _i12.BottomNavigationModel? param) =>
      (super.noSuchMethod(Invocation.method(#call, [param]),
          returnValue: Future<
                  _i3.Either<_i7.Failure, _i11.BottomNavigationEntity>>.value(
              _FakeEither_1<_i7.Failure, _i11.BottomNavigationEntity>())) as _i6
          .Future<_i3.Either<_i7.Failure, _i11.BottomNavigationEntity>>);
}

/// A class which mocks [GetActiveBottomNavigationUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetActiveBottomNavigationUsecase extends _i1.Mock
    implements _i13.GetActiveBottomNavigationUsecase {
  MockGetActiveBottomNavigationUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MainRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMainRepository_2()) as _i4.MainRepository);
  @override
  _i6.Future<_i3.Either<_i7.Failure, _i11.BottomNavigationEntity>> call(
          _i14.NoParam? param) =>
      (super.noSuchMethod(Invocation.method(#call, [param]),
          returnValue: Future<
                  _i3.Either<_i7.Failure, _i11.BottomNavigationEntity>>.value(
              _FakeEither_1<_i7.Failure, _i11.BottomNavigationEntity>())) as _i6
          .Future<_i3.Either<_i7.Failure, _i11.BottomNavigationEntity>>);
}
