// Mocks generated by Mockito 5.2.0 from annotations
// in crosscheck/test/features/dashboard/data/repositories/dashboard_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:crosscheck/core/network/network_info.dart' as _i5;
import 'package:crosscheck/features/dashboard/data/datasource/dashboard_remote_data_source.dart'
    as _i3;
import 'package:crosscheck/features/dashboard/data/models/data/dashboard_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDashboardModel_0 extends _i1.Fake implements _i2.DashboardModel {}

/// A class which mocks [DashboardRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRemoteDataSource extends _i1.Mock
    implements _i3.DashboardRemoteDataSource {
  MockDashboardRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DashboardModel> getDashboard(String? token) =>
      (super.noSuchMethod(Invocation.method(#getDashboard, [token]),
              returnValue:
                  Future<_i2.DashboardModel>.value(_FakeDashboardModel_0()))
          as _i4.Future<_i2.DashboardModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
