// Mocks generated by Mockito 5.2.0 from annotations
// in crosscheck/test/features/profile/data/respositories/profile_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:crosscheck/core/network/network_info.dart' as _i7;
import 'package:crosscheck/features/profile/data/datasource/profile_local_data_source.dart'
    as _i6;
import 'package:crosscheck/features/profile/data/datasource/profile_remote_data_source.dart'
    as _i4;
import 'package:crosscheck/features/profile/data/models/data/profile_model.dart'
    as _i3;
import 'package:crosscheck/features/profile/data/models/response/profile_response_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeProfileResponseModel_0 extends _i1.Fake
    implements _i2.ProfileResponseModel {}

class _FakeProfileModel_1 extends _i1.Fake implements _i3.ProfileModel {}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i4.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ProfileResponseModel> getProfile({String? token}) =>
      (super.noSuchMethod(Invocation.method(#getProfile, [], {#token: token}),
              returnValue: Future<_i2.ProfileResponseModel>.value(
                  _FakeProfileResponseModel_0()))
          as _i5.Future<_i2.ProfileResponseModel>);
}

/// A class which mocks [ProfileLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileLocalDataSource extends _i1.Mock
    implements _i6.ProfileLocalDataSource {
  MockProfileLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> setProfile(_i3.ProfileModel? profileModel) =>
      (super.noSuchMethod(Invocation.method(#setProfile, [profileModel]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<_i3.ProfileModel> getProfile() => (super.noSuchMethod(
          Invocation.method(#getProfile, []),
          returnValue: Future<_i3.ProfileModel>.value(_FakeProfileModel_1()))
      as _i5.Future<_i3.ProfileModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}
