// Mocks generated by Mockito 5.2.0 from annotations
// in crosscheck/test/features/walkthrough/data/repositories/walkthrough_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:crosscheck/features/walkthrough/data/datasource/walkthrough_local_data_source.dart'
    as _i2;
import 'package:crosscheck/features/walkthrough/data/models/request/walkthrough_params.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [WalkthroughLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalkthroughLocalDataSource extends _i1.Mock
    implements _i2.WalkthroughLocalDataSource {
  MockWalkthroughLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setIsSkip(_i4.WalkthroughParams? params) =>
      (super.noSuchMethod(Invocation.method(#setIsSkip, [params]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
