name: Crosscheck-CI
on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get All Dependencies
        run: flutter pub get
      - name: Run Lint
        run: flutter analyze
    
  unit-test:
    name: Unit Test
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Get All Dependencies
        run: flutter pub get
      - name: Run Test
        run: |
          flutter test test/features/*/data
          flutter test test/features/*/domain
          flutter test test/features/*/presentation/bloc
          flutter test test/features/*/presentation/*/bloc

  android-widget-test:
    name: Android Widget Test
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Create Android Emulator
        run: |
          echo $HOME
          ls -lah $ANDROID_HOME
          ls -lah $ANDROID_HOME/cmdline-tools
          ls -lah $ANDROID_HOME/cmdline-tools/latest
          ls -lah $ANDROID_HOME/cmdline-tools/latest/bin
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update --channel=0
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;google_apis;x86"
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager --verbose create avd --force --name "pixel_xl_30" --device "pixel" --package "system-images;android-30;google_apis;x86" --tag "google_apis" --abi "x86"
          echo "skin.name=1440x2560" >> ~/.android/avd/pixel_xl_30.avd/config.ini
          echo "hw.lcd.density=560" >> ~/.android/avd/pixel_xl_30.avd/config.ini
          echo "hw.keyboard=yes" >> ~/.android/avd/pixel_xl_30.avd/config.ini
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list avd
          echo "Starting emulator"
          $ANDROID_HOME/emulator/emulator -avd pixel_xl_30 -port 5037 -no-window -no-audio -debug-init > /dev/null 2>&1 &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
          $ANDROID_HOME/platform-tools/adb devices
          echo "Android Emulator started"
      - name: Flutter List devices
        run: flutter devices
      - name: Get All Dependencies
        run: flutter pub get
      - name: Run Wakthrough Test
        run: flutter test test/features/walkthrough/presentation/view -d "emulator-5037"
      - name: Run Register Test
        run: flutter test test/features/authentication/presentation/registration/view -d "emulator-5037"
      - name: Run Login Test
        run: flutter test test/features/authentication/presentation/login/view -d "emulator-5037"
      - name: Run Main Test
        run: flutter test test/features/main/presentation/view -d "emulator-5037"
      - name: Run Dashboard Test
        run: flutter test test/features/dashboard/presentation/view -d "emulator-5037"
      - name: Run Settings Test
        run: flutter test test/features/settings/presentation/view -d "emulator-5037"
      - name: Run Task Test
        run: flutter test test/features/task/presentation/view -d "emulator-5037"

  ios-widget-test:
    name: IOS Widget Test
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Create iOS Simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 15.2.simruntime
          xcrun simctl list runtimes
          UDID=$(xcrun simctl create "iPhone 11 Pro" "com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro" "com.apple.CoreSimulator.SimRuntime.iOS-15-2")
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
          echo "IOS Simulator Started"
          # xcrun simctl list devices
      - name: Flutter List devices
        run: | 
          flutter devices
      - name: Get All Dependencies
        run: flutter pub get
      - name: Run Wakthrough Test
        run: flutter test test/features/walkthrough/presentation/view -d "iPhone 11 Pro"
      - name: Run Register Test
        run: flutter test test/features/authentication/presentation/registration/view -d "iPhone 11 Pro"
      - name: Run Login Test
        run: flutter test test/features/authentication/presentation/login/view -d "iPhone 11 Pro"
      - name: Run Main Test
        run: flutter test test/features/main/presentation/view -d "iPhone 11 Pro"
      - name: Run Dashboard Test
        run: flutter test test/features/dashboard/presentation/view -d "iPhone 11 Pro"
      - name: Run Settings Test
        run: flutter test test/features/settings/presentation/view -d "iPhone 11 Pro"
      - name: Run Task Test
        run: flutter test test/features/task/presentation/view -d "iPhone 11 Pro"

  # build_ios:
  #   name: Build iOS
  #   needs: [test]
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v2
  #       with:
  #         distribution: 'zulu'
  #         java-version: '11'
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #     - run: flutter pub get
  #     - run: flutter clean
  #     - run: flutter build ios

  # build_android:
  #   name: Build Android
  #   needs: [test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v2
  #       with:
  #         distribution: 'zulu'
  #         java-version: '11'
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #     - run: flutter pub get
  #     - run: flutter clean
  #     - run: flutter build apk